version: "2.1"
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/rutrum/docker/jellyfin/config:/config
      - /home/rutrum/barracuda/media:/data
    ports:
      - 8096:8096
      - 7359:7359/udp # client discovery
      - 1900:1900/udp # DNLA and clients
    restart: unless-stopped
