#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

# bare minimum keybindings in case nothing else loads
hc keybind Mod1-Return spawn alacritty
hc keybind Mod1-Shift-r reload

HCDIR=/home/rutrum/.config/herbstluftwm

hc emit_hook reload

# Load bar
/home/rutrum/scripts/startpolybar

# Restart compositing
pkill picom
picom &

# Set background
feh --bg-fill /home/rutrum/barracuda/media/wallpapers/mushroom_forest_fixed.png

# Set resolution and framerate
xrandr --output DP-0 --mode 3840x1600 --rate 120

# start syncthing
# syncthing serve --no-browser --logfile=default

# remove all existing keybindings
hc keyunbind --all

# hc lock

# load keybindings
. $HCDIR/keybindings.sh

# load theme
. $HCDIR/theme.sh

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'
hc set default_frame_layout horizontal

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 2560x1600+0+0 1280x1600+2560+0
# or simply:
hc detect_monitors

# find the panel
#panel=~/.config/herbstluftwm/panel.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
#for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    #"$panel" $monitor &
#done

# Sets padding of monitor 0 with 0,0,30,0
hc pad 0 0 0 35 0
